#if UNITY_ANDROID
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor.Android;
using UnityEngine;

namespace Alogame.SDK.Editor
{
    /// <summary>
    /// Declares the native SDK's runtime dependencies in the generated Gradle project.
    ///
    /// Why this is necessary: oeg-sdk.aar is vendored as a plain file, not resolved from a
    /// Maven coordinate, so it carries no POM and Gradle has no way to learn its transitive
    /// dependencies. The APK still builds and installs perfectly — it dies at runtime on the
    /// first call that touches a missing class, e.g.
    ///
    ///     java.lang.NoClassDefFoundError: Failed resolution of: Lretrofit2/Retrofit;
    ///
    /// Declared as Gradle coordinates rather than shipping jars in Plugins/Android on purpose:
    /// a raw jar collides with the host game's own copy (duplicate classes at dex-merge time)
    /// in any project that already uses it, whereas a coordinate lets Gradle resolve one
    /// version for everyone. Appending is additive — no existing configuration is rewritten,
    /// which is the constraint a plugin sharing a project with others has to respect.
    ///
    /// The list is transcribed from v2/android/sdk/build.gradle.kts, NOT from the POM that
    /// v2/release/build.gradle generates: that POM is missing androidx.credentials,
    /// googleid and both Firebase artifacts, so copying it would break Google login and push.
    /// </summary>
    public sealed class AlogameAndroidPostprocessBuild : IPostGenerateGradleAndroidProject
    {
        private const string Tag = "[Alogame SDK]";

        /// <summary>Marks the block this class appends, so a re-export is idempotent.</summary>
        private const string Marker = "// --- Alogame SDK (generated by AlogameAndroidPostprocessBuild) ---";

        /// <summary>
        /// Firebase artifacts carry no version: the BOM below pins them. Everything else is
        /// pinned to the version the AAR was compiled against.
        /// </summary>
        private const string FirebaseBom = "com.google.firebase:firebase-bom:32.7.0";

        private static readonly string[] Required =
        {
            // Kotlin runtime — the SDK is Kotlin, and its enums compile against
            // kotlin.enums.EnumEntriesKt, so the stdlib is not optional.
            "org.jetbrains.kotlin:kotlin-stdlib:2.0.21",
            "org.jetbrains.kotlin:kotlin-parcelize-runtime:2.0.21",

            // AndroidX / UI — the SDK ships its own login and payment screens.
            "androidx.core:core-ktx:1.12.0",
            "androidx.appcompat:appcompat:1.6.1",
            "androidx.activity:activity-ktx:1.8.2",
            "androidx.fragment:fragment-ktx:1.6.2",
            "androidx.constraintlayout:constraintlayout:2.1.4",
            "com.google.android.material:material:1.11.0",
            "androidx.cardview:cardview:1.0.0",
            "androidx.browser:browser:1.8.0",

            "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3",

            // Networking
            "com.squareup.retrofit2:retrofit:2.9.0",
            "com.squareup.retrofit2:converter-gson:2.9.0",
            "com.squareup.okhttp3:okhttp:4.12.0",
            "com.squareup.okhttp3:logging-interceptor:4.12.0",
            "com.google.code.gson:gson:2.10.1",

            "androidx.security:security-crypto:1.1.0-alpha06",
            "com.jakewharton.timber:timber:5.0.1",

            // Google login via Credential Manager (the modern replacement for GoogleSignIn).
            "androidx.credentials:credentials:1.3.0",
            "androidx.credentials:credentials-play-services-auth:1.3.0",
            "com.google.android.libraries.identity.googleid:googleid:1.1.0",

            // Analytics
            "com.adjust.sdk:adjust-android:5.0.0",
            "com.android.installreferrer:installreferrer:2.2",

            // In-app purchase
            "com.android.billingclient:billing-ktx:8.0.0",
        };

        /// <summary>
        /// BOM-managed, so these are declared without a version.
        /// The SDK deliberately does NOT apply the com.google.gms.google-services plugin —
        /// that stays the host game's responsibility, because applying it without a
        /// google-services.json fails the build for every game that has no Firebase config.
        /// </summary>
        private static readonly string[] FirebaseArtifacts =
        {
            "com.google.firebase:firebase-messaging-ktx",
            "com.google.firebase:firebase-analytics-ktx",
        };

        /// <summary>
        /// compileOnly in the SDK build, so they are absent unless the game turns the provider
        /// on. Gated on the same settings asset that drives the manifest entries in
        /// AlogameBuildPostprocessor — enabling a provider in one place and not the other would
        /// produce a manifest referencing classes that are not on the classpath.
        /// </summary>
        private static readonly string[] FacebookOptional =
        {
            "com.facebook.android:facebook-login:16.0.0",
        };

        private static readonly string[] TikTokOptional =
        {
            "com.tiktok.open.sdk:tiktok-open-sdk-core:2.3.0",
            "com.tiktok.open.sdk:tiktok-open-sdk-auth:2.3.0",
        };

        // Runs after Unity's own Gradle generation. Ordering against other plugins does not
        // matter because this only appends.
        public int callbackOrder => 100;

        public void OnPostGenerateGradleAndroidProject(string path)
        {
            var buildFile = Path.Combine(path, "build.gradle");
            if (!File.Exists(buildFile))
            {
                // Unity 2023+/6 can emit Kotlin-DSL build files instead.
                buildFile = Path.Combine(path, "build.gradle.kts");
                if (!File.Exists(buildFile))
                {
                    Debug.LogError(Tag + " no build.gradle in " + path + " — could not declare the SDK's " +
                                   "dependencies. The APK will build and then throw NoClassDefFoundError at runtime.");
                    return;
                }
            }

            var text = File.ReadAllText(buildFile);
            if (text.Contains(Marker))
            {
                Debug.Log(Tag + " dependencies already declared — nothing to do.");
                return;
            }

            var isKts = buildFile.EndsWith(".kts");
            var block = BuildDependencyBlock(isKts);

            // Match the first `dependencies {` at the start of a line so that a `dependencies`
            // inside buildscript{} or a comment is not hit.
            var match = Regex.Match(text, @"(?m)^dependencies\s*\{");
            text = match.Success
                ? text.Insert(match.Index + match.Length, "\n" + block)
                : text + "\n\ndependencies {\n" + block + "}\n";

            File.WriteAllText(buildFile, text);
            Debug.Log(Tag + " declared the native SDK's dependencies in " + Path.GetFileName(buildFile) + ".");
        }

        private static string BuildDependencyBlock(bool isKts)
        {
            var settings = AlogameSDKSettings.LoadOrNull();
            var coordinates = new List<string>(Required);

            if (settings != null && settings.enableFacebookLogin) coordinates.AddRange(FacebookOptional);
            if (settings != null && settings.enableTikTokLogin) coordinates.AddRange(TikTokOptional);

            var sb = new StringBuilder();
            sb.Append("    ").Append(Marker).Append('\n');

            // The BOM must come first so the versionless Firebase artifacts below resolve.
            sb.Append(Line(isKts, "platform(\"" + FirebaseBom + "\")", raw: true)).Append('\n');
            foreach (var artifact in FirebaseArtifacts) sb.Append(Line(isKts, artifact)).Append('\n');
            foreach (var coordinate in coordinates) sb.Append(Line(isKts, coordinate)).Append('\n');

            return sb.ToString();
        }

        /// <summary>
        /// `raw` passes the argument through untouched, for wrappers like platform(...) that
        /// are already an expression rather than a bare coordinate string.
        /// </summary>
        private static string Line(bool isKts, string coordinate, bool raw = false)
        {
            if (raw) return isKts ? "    implementation(" + coordinate + ")" : "    implementation " + coordinate;
            return isKts
                ? "    implementation(\"" + coordinate + "\")"
                : "    implementation '" + coordinate + "'";
        }
    }
}
#endif
