#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef OEGSDKV2_SWIFT_H
#define OEGSDKV2_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="OegSdkV2",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import StoreKit;
@import UIKit;
@import UserNotifications;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="OegSdkV2",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_ENUM_FWD_DECL(NSInteger, OEGActionType)
@class NSError;
@class UIViewController;
SWIFT_ENUM_FWD_DECL(NSInteger, OEGIAPStatus)
@class NSURL;
@class NSUserActivity;
@class UIApplication;
@class NSData;
/// Legacy-compatible manager for backward compatibility with existing ObjC games.
/// This class provides the same API as the legacy OEGFramework’s OEGManager,
/// delegating all functionality to the modern OEGAuth implementation.
/// <h2>Usage (Objective-C - exactly like legacy SDK)</h2>
/// \code
/// // Login
/// [[OEGManager sharedManager] showLoginWithCallback:^(OEGActionType type, id response, BOOL success, NSError *error) {
///     if (success) {
///         NSLog(@"Logged in!");
///     }
/// }];
///
/// // Get token
/// NSString *token = [OEGManager getAPIToken];
///
/// \endcode<h2>For New Games</h2>
/// Use <code>OEGAuth</code> instead for modern Swift async/await API.
SWIFT_CLASS("_TtC8OegSdkV210OEGManager")
@interface OEGManager : NSObject
/// Shared manager instance (legacy pattern)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OEGManager * _Nonnull sharedManager;)
+ (OEGManager * _Nonnull)sharedManager SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Get current API token
///
/// returns:
/// JWT token if logged in, nil otherwise
+ (NSString * _Nullable)getAPIToken SWIFT_WARN_UNUSED_RESULT;
/// Get current user UUID
///
/// returns:
/// User UUID if logged in, nil otherwise
+ (NSString * _Nullable)getAPIUUID SWIFT_WARN_UNUSED_RESULT;
/// Check if current user is a guest (PlayNow)
///
/// returns:
/// true if guest account, false otherwise
+ (BOOL)isPlayNow SWIFT_WARN_UNUSED_RESULT;
/// Get current user ID (numeric OEG user ID, not UUID).
/// Mirrors Android OEGAuth.getCurrentUser()?.userId.
///
/// returns:
/// userId string if logged in, nil otherwise
+ (NSString * _Nullable)getUserId SWIFT_WARN_UNUSED_RESULT;
/// Get current user info as a dictionary (ObjC-compatible equivalent of currentUser).
/// Returns nil if no user is logged in.
/// Keys: userId, uuid, token, isGuest, username, displayName, email, avatar, phone, fullname, birthday, gender, address
+ (NSDictionary<NSString *, id> * _Nullable)getCurrentUser SWIFT_WARN_UNUSED_RESULT;
/// Get device info as a dictionary (ObjC-compatible equivalent of Swift <code>OEGAuth.shared.getDeviceInfo()</code>).
/// Mirrors Android <code>OEGAuth.getDeviceInfo()</code>.
/// Keys: osId (2 = iOS), deviceId, sdkId, packageName, gameVersion, gameId
+ (NSDictionary<NSString *, id> * _Nonnull)getDeviceInfo SWIFT_WARN_UNUSED_RESULT;
/// Show login UI with callback
/// \param callback Callback with action type, response, success flag, and optional error
///
- (void)showLoginWithCallback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Show login UI from specific view controller
/// \param viewController Presenting view controller (uses top VC if nil)
///
/// \param callback Callback with action type, response, success flag, and optional error
///
- (void)showLoginWithViewController:(UIViewController * _Nullable)viewController callback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Show profile UI (Update Profile)
/// \param callback Callback with updated user info
///
- (void)showProfileWithCallback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Show profile UI from specific view controller
/// \param viewController Presenting view controller
///
/// \param callback Callback with updated user info
///
- (void)showProfileWithViewController:(UIViewController * _Nullable)viewController callback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Show profile UI with merge option (Not implemented yet, falls back to standard profile)
- (void)showProfileWithViewController:(UIViewController * _Nullable)viewController isMergeAccount:(BOOL)isMergeAccount callback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Show change password UI
/// \param callback Callback with result
///
- (void)showResetPasswordWithCallback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Show change password UI from specific view controller
- (void)showResetPasswordWithViewController:(UIViewController * _Nullable)viewController callback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Logout current user
- (void)logout;
/// Check if IAP is available for level
/// \param level Game level
///
///
/// returns:
/// true if IAP is available
- (BOOL)isIAP:(int32_t)level SWIFT_WARN_UNUSED_RESULT;
/// Process in-app purchase
/// \param serverID Game server ID
///
/// \param roleID Player role ID
///
/// \param levels Current level
///
/// \param accountID Account ID (optional)
///
/// \param productID Store product ID
///
/// \param extInfo Extra info
///
/// \param callback IAP result callback
///
- (void)inAppPurchaseWithServerID:(NSString * _Nonnull)serverID roleID:(NSString * _Nonnull)roleID levels:(NSString * _Nonnull)levels accountID:(NSString * _Nullable)accountID productID:(NSString * _Nullable)productID extInfo:(NSString * _Nonnull)extInfo callback:(void (^ _Nonnull)(enum OEGIAPStatus, NSString * _Nonnull, NSError * _Nullable))callback;
/// Handle app launch — initializes full SDK (Auth, Analytics, Payment, Push, Social)
+ (void)handleDidFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)options;
/// Handle app becoming active
+ (void)handleDidBecomeActive;
/// Handle app resigning active
+ (void)handleWillResignActive;
/// Handle app entering background
+ (void)handleDidEnterBackground;
/// Handle app entering foreground
+ (void)handleWillEnterForeground;
/// Handle app termination
+ (void)handleWillTerminate;
/// Handle URL open (for social login OAuth callbacks)
+ (BOOL)handleOpenURL:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
/// Handle Universal Links (required for TikTok web auth callback).
/// Call from application(_:continue:restorationHandler:) in AppDelegate.
+ (BOOL)handleContinueUserActivity:(NSUserActivity * _Nonnull)userActivity;
/// Register for remote notifications
+ (void)registerForRemoteNotifications:(UIApplication * _Nonnull)application;
/// Handle device token registration
+ (void)handleDidRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
/// Handle received remote notification
+ (void)handleRemoteNotification:(NSDictionary * _Nonnull)userInfo;
/// Log event for analytics
/// \param eventName Event name
///
/// \param values Event parameters
///
- (void)logEvent:(NSString * _Nonnull)eventName withValues:(NSDictionary<NSString *, id> * _Nullable)values;
/// Log an event that carries revenue (recharge / web_store / custom revenue events).
/// Sets the REAL Adjust revenue on this event’s own token — required for revenue to appear on
/// the dashboard (a plain <code>logEvent</code> only sends the amount as a callback parameter = 0 revenue).
/// \param eventName Event name / token that records the revenue (e.g. “Recharge”)
///
/// \param values Event parameters
///
/// \param revenue Amount (> 0)
///
/// \param currency ISO 4217 code (e.g. “VND”)
///
/// \param orderId Unique order id for deduplication
///
- (void)logEvent:(NSString * _Nonnull)eventName withValues:(NSDictionary<NSString *, id> * _Nullable)values revenue:(double)revenue currency:(NSString * _Nonnull)currency orderId:(NSString * _Nullable)orderId;
@end

/// Alogame-branded entry point for new games. Identical to <code>OEGManager</code> — every method is
/// inherited, nothing is reimplemented — so behavior never drifts between the two names.
/// <code>OEGManager</code> keeps working unchanged for existing integrations; this class exists only to
/// give new games an Alogame-branded symbol to call instead.
/// <h2>Usage (Objective-C)</h2>
/// \code
/// [[AlogameManager sharedManager] showLoginWithCallback:^(OEGActionType type, id response, BOOL success, NSError *error) {
///     if (success) {
///         NSLog(@"Logged in!");
///     }
/// }];
///
/// \endcode
SWIFT_CLASS("_TtC8OegSdkV214AlogameManager")
@interface AlogameManager : OEGManager
@end

@class NSBundle;
@class NSCoder;
SWIFT_CLASS("_TtC8OegSdkV228ForgotPasswordViewController")
@interface ForgotPasswordViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8OegSdkV219LoginViewController")
@interface LoginViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

/// Action types returned in OEGAccountCallback
/// Matches legacy OEGManager.h enum values exactly
typedef SWIFT_ENUM(NSInteger, OEGActionType, open) {
  OEGActionTypeRegister = 0,
  OEGActionTypeLoginOEGID = 1,
  OEGActionTypeLoginFacebook = 2,
  OEGActionTypeLoginGoogle = 3,
  OEGActionTypeLoginApple = 4,
  OEGActionTypePlaynow = 5,
  OEGActionTypeLogout = 6,
  OEGActionTypeProfile = 7,
  OEGActionTypeChangePassword = 8,
  OEGActionTypeForgotPassword = 9,
  OEGActionTypeVerifyEmail = 10,
  OEGActionTypeVerifyPhone = 11,
  OEGActionTypeClose = 12,
};

SWIFT_ENUM_FWD_DECL(NSInteger, Environment)
/// OEG Analytics SDK - Adjust Integration
/// Matches Android’s <code>OEGAnalytics</code> public API structure.
SWIFT_CLASS("_TtC8OegSdkV212OEGAnalytics")
@interface OEGAnalytics : NSObject
/// Shared singleton instance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OEGAnalytics * _Nonnull shared;)
+ (OEGAnalytics * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Initialize Adjust SDK
/// \param appToken Adjust App Token
///
/// \param environment Sandbox or Production
///
/// \param eventTokenMap Optional mapping of event names to tokens
///
- (void)initializeWithAppToken:(NSString * _Nonnull)appToken environment:(enum Environment)environment eventTokenMap:(NSDictionary<NSString *, NSString *> * _Nonnull)eventTokenMap;
/// Track an event
/// \param eventNameOrToken Event name (from mapping) or direct token
///
/// \param parameters Optional callback parameters
///
- (void)logEvent:(NSString * _Nonnull)eventNameOrToken parameters:(NSDictionary<NSString *, NSString *> * _Nullable)parameters;
/// Track a purchase/revenue event
/// \param eventToken Adjust event token
///
/// \param price Amount
///
/// \param currency Currency code (USD, VND)
///
/// \param transactionId Unique transaction ID
///
/// \param productId Product ID
///
- (void)logPurchaseWithEventToken:(NSString * _Nonnull)eventToken price:(double)price currency:(NSString * _Nonnull)currency transactionId:(NSString * _Nullable)transactionId productId:(NSString * _Nullable)productId parameters:(NSDictionary<NSString *, NSString *> * _Nullable)parameters;
/// Track an event that carries revenue, keyed on the event’s own token.
/// Use for recharge / web_store / custom revenue events (e.g. first_recharge) where the game
/// dev must set the real Adjust revenue — passing the amount as a plain parameter does NOT count.
/// \param eventNameOrToken Event name (from mapping) or direct token — this is the Adjust event that records the revenue
///
/// \param revenue Amount (must be > 0 to be recorded)
///
/// \param currency ISO 4217 code (e.g. “VND”, “USD”)
///
/// \param orderId Unique order/transaction id for deduplication
///
/// \param parameters Optional extra callback parameters
///
- (void)logRevenue:(NSString * _Nonnull)eventNameOrToken revenue:(double)revenue currency:(NSString * _Nonnull)currency orderId:(NSString * _Nullable)orderId parameters:(NSDictionary<NSString *, NSString *> * _Nullable)parameters;
/// Enable/disable tracking (GDPR compliance)
- (void)setTrackingEnabled:(BOOL)enabled;
/// Legacy backward compatible method for tracking events with parameters
- (void)trackEventToken:(NSString * _Nonnull)eventToken parameters:(NSDictionary<NSString *, NSString *> * _Nullable)parameters;
/// Legacy backward compatible method for tracking revenue with parameters
- (void)trackEventToken:(NSString * _Nonnull)eventToken revenue:(double)revenue currency:(NSString * _Nullable)currency transactionId:(NSString * _Nullable)transactionId parameters:(NSDictionary<NSString *, NSString *> * _Nullable)parameters;
@end

/// Adjust environment enum
typedef SWIFT_ENUM(NSInteger, Environment, open) {
  EnvironmentSandbox = 0,
  EnvironmentProduction = 1,
};

/// Protocol for Unity/Native callbacks.
/// Designed to be implemented by native bridges.
/// Matches Android’s <code>OEGCallback</code> interface.
SWIFT_PROTOCOL("_TtP8OegSdkV211OEGCallback_")
@protocol OEGCallback
- (void)onSuccessWithPayload:(NSString * _Nonnull)payload;
- (void)onErrorWithCode:(NSInteger)code message:(NSString * _Nonnull)message;
@end

/// IAP status returned in OEGIAPCallback
/// Matches legacy OEGManager.h enum values exactly
typedef SWIFT_ENUM(NSInteger, OEGIAPStatus, open) {
  OEGIAPStatusPurchasing = 0,
  OEGIAPStatusPurchased = 1,
  OEGIAPStatusRestored = 2,
  OEGIAPStatusFailed = 3,
  OEGIAPStatusRequestError = 4,
  OEGIAPStatusVerified = 5,
};

/// OEG Payment SDK - StoreKit Integration
/// Provides in-app purchase functionality using StoreKit 2 (iOS 15+) or StoreKit 1 fallback.
/// Matches Android’s <code>OEGPayment</code> public API structure.
SWIFT_CLASS("_TtC8OegSdkV210OEGPayment") SWIFT_AVAILABILITY(ios,introduced=13.0) SWIFT_AVAILABILITY(macos,introduced=10.15)
@interface OEGPayment : NSObject
/// Shared singleton instance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OEGPayment * _Nonnull shared;)
+ (OEGPayment * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SKProductsRequest;
@class SKProductsResponse;
@class SKRequest;
@class SKPaymentQueue;
@class SKPaymentTransaction;
@interface OEGPayment (SWIFT_EXTENSION(OegSdkV2)) <SKPaymentTransactionObserver, SKProductsRequestDelegate>
- (void)productsRequest:(SKProductsRequest * _Nonnull)request didReceiveResponse:(SKProductsResponse * _Nonnull)response;
- (void)request:(SKRequest * _Nonnull)request didFailWithError:(NSError * _Nonnull)error;
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue updatedTransactions:(NSArray<SKPaymentTransaction *> * _Nonnull)transactions;
@end

@protocol OEGPushDelegate;
@class UNUserNotificationCenter;
@class UNNotification;
/// Decoupled Push Notification Manager.
/// Handles permission requests and token management.
/// Host app should pass the device token (APNS or FCM) via <code>setDeviceToken</code>.
SWIFT_CLASS("_TtC8OegSdkV27OEGPush") SWIFT_AVAILABILITY(ios,introduced=10.0) SWIFT_AVAILABILITY(macos,introduced=10.14)
@interface OEGPush : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OEGPush * _Nonnull shared;)
+ (OEGPush * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Request Push Notification Permission
/// \param completion (Granted, Error?)
///
- (void)requestAuthorizationWithCompletion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
/// Request the OS notification permission.
/// Unified with Android <code>OEGPush.requestNotificationPermission(callback:)</code> — same name,
/// same <code>granted: Bool</code> result. Use this from cross-platform code; on iOS it wraps
/// <code>requestAuthorization</code> and drops the error. [completion] is invoked on the main thread.
- (void)requestNotificationPermissionWithCompletion:(void (^ _Nonnull)(BOOL))completion;
/// Set the device token (Hex String or FCM Token)
/// \param token String representation of the token
///
- (void)setDeviceToken:(NSString * _Nonnull)token;
/// Helper to convert APNS Data to Hex String
- (void)didRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
- (void)registerForPushNotificationsWithApplication:(UIApplication * _Nonnull)application;
- (void)didRegisterWithToken:(NSData * _Nonnull)deviceToken;
/// Delegate for exposing push data to game engines (Cocos Creator, Egret, Unity)
@property (nonatomic, weak) id <OEGPushDelegate> _Nullable delegate;
/// Handle incoming remote notification data payload
/// \param userInfo The notification payload dictionary
///
- (void)handleRemoteNotification:(NSDictionary * _Nonnull)userInfo;
/// Handle incoming notification (foreground)
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center willPresent:(UNNotification * _Nonnull)notification withCompletionHandler:(void (^ _Nonnull)(UNNotificationPresentationOptions))completionHandler;
@end

/// Protocol for game engines to receive push notification data
SWIFT_PROTOCOL("_TtP8OegSdkV215OEGPushDelegate_")
@protocol OEGPushDelegate
@optional
/// Called when a push notification is received
- (void)oegPushDidReceiveNotificationWithUserInfo:(NSDictionary * _Nonnull)userInfo;
/// Called when device token is updated
- (void)oegPushDidUpdateToken:(NSString * _Nonnull)token;
@end

/// Main entry point for OEG SDK v2.
/// Matches Android’s <code>OEGFrameworks</code> singleton but renamed to <code>OegSdkCore</code> per convention.
SWIFT_CLASS("_TtC8OegSdkV210OegSdkCore") SWIFT_AVAILABILITY(ios,introduced=13.0) SWIFT_AVAILABILITY(macos,introduced=10.15)
@interface OegSdkCore : NSObject
/// Shared singleton instance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OegSdkCore * _Nonnull shared;)
+ (OegSdkCore * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Initialization state
@property (nonatomic, readonly) BOOL isInitialized;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Check if SDK is ready
- (BOOL)checkInitialized SWIFT_WARN_UNUSED_RESULT;
/// Set the active Game Character/Role info (for tracking and dashboard display).
/// This is a convenience method that delegates to OEGAuth.shared.setGameRole().
/// \param serverId Server ID (required)
///
/// \param serverName Server display name (optional)
///
/// \param roleId Character/Role ID (required)
///
/// \param roleName Character/Role display name (optional)
///
/// \param level Character level (optional)
///
+ (void)setGameRoleWithServerId:(NSString * _Nonnull)serverId serverName:(NSString * _Nullable)serverName roleId:(NSString * _Nonnull)roleId roleName:(NSString * _Nullable)roleName level:(NSInteger)level;
/// Clear the active Game Character/Role without logging the account out.
/// This is a convenience method that delegates to OEGAuth.shared.logoutGameRole().
/// The SDK only clears its own state, then invokes <code>callback</code> — it does not navigate
/// anywhere. Use the callback to move the game to its own switch-server screen.
+ (void)logoutGameRoleWithCallback:(void (^ _Nonnull)(void))callback;
/// The active Game Character/Role, as a dictionary — <code>nil</code> if none is set. <code>OEGGameRole</code> is
/// a Swift struct and can’t be bridged to Objective-C directly, so this is the ObjC-visible
/// equivalent of reading <code>OEGAuth.gameRole</code> from Swift. Keys: serverId, serverName, roleId,
/// roleName (all NSString, absent when not provided), level (NSNumber, absent when not set).
+ (NSDictionary<NSString *, id> * _Nullable)getGameRole SWIFT_WARN_UNUSED_RESULT;
@end

/// Builder for constructing SDK configuration
SWIFT_CLASS("_TtCC8OegSdkV210OegSdkCore7Builder")
@interface Builder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (Builder * _Nonnull)setGameId:(NSInteger)gameId SWIFT_WARN_UNUSED_RESULT;
- (Builder * _Nonnull)setApiBaseUrl:(NSString * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
/// Selects the hardcoded dev vs. production API host (see SdkEnvironment).
/// Ignored if setApiBaseUrl was also called.
- (Builder * _Nonnull)setDebugEnv:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (Builder * _Nonnull)setSentryDsn:(NSString * _Nonnull)dsn SWIFT_WARN_UNUSED_RESULT;
- (Builder * _Nonnull)setAdjustConfigWithAppToken:(NSString * _Nonnull)appToken environment:(NSString * _Nonnull)environment SWIFT_WARN_UNUSED_RESULT;
/// Set the maintain polling interval in seconds.
/// Default: 60. Minimum: 30 (clamped). 0 disables polling entirely.
- (Builder * _Nonnull)setMaintainPollingInterval:(NSInteger)seconds SWIFT_WARN_UNUSED_RESULT;
- (void)build;
@end

SWIFT_CLASS("_TtC8OegSdkV221ProfileViewController")
@interface ProfileViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8OegSdkV227ResetPasswordViewController")
@interface ResetPasswordViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8OegSdkV227UpdateProfileViewController")
@interface UpdateProfileViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8OegSdkV220VerifyViewController")
@interface VerifyViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef OEGSDKV2_SWIFT_H
#define OEGSDKV2_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="OegSdkV2",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import StoreKit;
@import UIKit;
@import UserNotifications;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="OegSdkV2",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_ENUM_FWD_DECL(NSInteger, OEGActionType)
@class NSError;
@class UIViewController;
SWIFT_ENUM_FWD_DECL(NSInteger, OEGIAPStatus)
@class NSURL;
@class NSUserActivity;
@class UIApplication;
@class NSData;
/// Legacy-compatible manager for backward compatibility with existing ObjC games.
/// This class provides the same API as the legacy OEGFramework’s OEGManager,
/// delegating all functionality to the modern OEGAuth implementation.
/// <h2>Usage (Objective-C - exactly like legacy SDK)</h2>
/// \code
/// // Login
/// [[OEGManager sharedManager] showLoginWithCallback:^(OEGActionType type, id response, BOOL success, NSError *error) {
///     if (success) {
///         NSLog(@"Logged in!");
///     }
/// }];
///
/// // Get token
/// NSString *token = [OEGManager getAPIToken];
///
/// \endcode<h2>For New Games</h2>
/// Use <code>OEGAuth</code> instead for modern Swift async/await API.
SWIFT_CLASS("_TtC8OegSdkV210OEGManager")
@interface OEGManager : NSObject
/// Shared manager instance (legacy pattern)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OEGManager * _Nonnull sharedManager;)
+ (OEGManager * _Nonnull)sharedManager SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Get current API token
///
/// returns:
/// JWT token if logged in, nil otherwise
+ (NSString * _Nullable)getAPIToken SWIFT_WARN_UNUSED_RESULT;
/// Get current user UUID
///
/// returns:
/// User UUID if logged in, nil otherwise
+ (NSString * _Nullable)getAPIUUID SWIFT_WARN_UNUSED_RESULT;
/// Check if current user is a guest (PlayNow)
///
/// returns:
/// true if guest account, false otherwise
+ (BOOL)isPlayNow SWIFT_WARN_UNUSED_RESULT;
/// Get current user ID (numeric OEG user ID, not UUID).
/// Mirrors Android OEGAuth.getCurrentUser()?.userId.
///
/// returns:
/// userId string if logged in, nil otherwise
+ (NSString * _Nullable)getUserId SWIFT_WARN_UNUSED_RESULT;
/// Get current user info as a dictionary (ObjC-compatible equivalent of currentUser).
/// Returns nil if no user is logged in.
/// Keys: userId, uuid, token, isGuest, username, displayName, email, avatar, phone, fullname, birthday, gender, address
+ (NSDictionary<NSString *, id> * _Nullable)getCurrentUser SWIFT_WARN_UNUSED_RESULT;
/// Get device info as a dictionary (ObjC-compatible equivalent of Swift <code>OEGAuth.shared.getDeviceInfo()</code>).
/// Mirrors Android <code>OEGAuth.getDeviceInfo()</code>.
/// Keys: osId (2 = iOS), deviceId, sdkId, packageName, gameVersion, gameId
+ (NSDictionary<NSString *, id> * _Nonnull)getDeviceInfo SWIFT_WARN_UNUSED_RESULT;
/// Show login UI with callback
/// \param callback Callback with action type, response, success flag, and optional error
///
- (void)showLoginWithCallback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Show login UI from specific view controller
/// \param viewController Presenting view controller (uses top VC if nil)
///
/// \param callback Callback with action type, response, success flag, and optional error
///
- (void)showLoginWithViewController:(UIViewController * _Nullable)viewController callback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Show profile UI (Update Profile)
/// \param callback Callback with updated user info
///
- (void)showProfileWithCallback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Show profile UI from specific view controller
/// \param viewController Presenting view controller
///
/// \param callback Callback with updated user info
///
- (void)showProfileWithViewController:(UIViewController * _Nullable)viewController callback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Show profile UI with merge option (Not implemented yet, falls back to standard profile)
- (void)showProfileWithViewController:(UIViewController * _Nullable)viewController isMergeAccount:(BOOL)isMergeAccount callback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Show change password UI
/// \param callback Callback with result
///
- (void)showResetPasswordWithCallback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Show change password UI from specific view controller
- (void)showResetPasswordWithViewController:(UIViewController * _Nullable)viewController callback:(void (^ _Nonnull)(enum OEGActionType, id _Nullable, BOOL, NSError * _Nullable))callback;
/// Logout current user
- (void)logout;
/// Check if IAP is available for level
/// \param level Game level
///
///
/// returns:
/// true if IAP is available
- (BOOL)isIAP:(int32_t)level SWIFT_WARN_UNUSED_RESULT;
/// Process in-app purchase
/// \param serverID Game server ID
///
/// \param roleID Player role ID
///
/// \param levels Current level
///
/// \param accountID Account ID (optional)
///
/// \param productID Store product ID
///
/// \param extInfo Extra info
///
/// \param callback IAP result callback
///
- (void)inAppPurchaseWithServerID:(NSString * _Nonnull)serverID roleID:(NSString * _Nonnull)roleID levels:(NSString * _Nonnull)levels accountID:(NSString * _Nullable)accountID productID:(NSString * _Nullable)productID extInfo:(NSString * _Nonnull)extInfo callback:(void (^ _Nonnull)(enum OEGIAPStatus, NSString * _Nonnull, NSError * _Nullable))callback;
/// Handle app launch — initializes full SDK (Auth, Analytics, Payment, Push, Social)
+ (void)handleDidFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)options;
/// Handle app becoming active
+ (void)handleDidBecomeActive;
/// Handle app resigning active
+ (void)handleWillResignActive;
/// Handle app entering background
+ (void)handleDidEnterBackground;
/// Handle app entering foreground
+ (void)handleWillEnterForeground;
/// Handle app termination
+ (void)handleWillTerminate;
/// Handle URL open (for social login OAuth callbacks)
+ (BOOL)handleOpenURL:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
/// Handle Universal Links (required for TikTok web auth callback).
/// Call from application(_:continue:restorationHandler:) in AppDelegate.
+ (BOOL)handleContinueUserActivity:(NSUserActivity * _Nonnull)userActivity;
/// Register for remote notifications
+ (void)registerForRemoteNotifications:(UIApplication * _Nonnull)application;
/// Handle device token registration
+ (void)handleDidRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
/// Handle received remote notification
+ (void)handleRemoteNotification:(NSDictionary * _Nonnull)userInfo;
/// Log event for analytics
/// \param eventName Event name
///
/// \param values Event parameters
///
- (void)logEvent:(NSString * _Nonnull)eventName withValues:(NSDictionary<NSString *, id> * _Nullable)values;
/// Log an event that carries revenue (recharge / web_store / custom revenue events).
/// Sets the REAL Adjust revenue on this event’s own token — required for revenue to appear on
/// the dashboard (a plain <code>logEvent</code> only sends the amount as a callback parameter = 0 revenue).
/// \param eventName Event name / token that records the revenue (e.g. “Recharge”)
///
/// \param values Event parameters
///
/// \param revenue Amount (> 0)
///
/// \param currency ISO 4217 code (e.g. “VND”)
///
/// \param orderId Unique order id for deduplication
///
- (void)logEvent:(NSString * _Nonnull)eventName withValues:(NSDictionary<NSString *, id> * _Nullable)values revenue:(double)revenue currency:(NSString * _Nonnull)currency orderId:(NSString * _Nullable)orderId;
@end

/// Alogame-branded entry point for new games. Identical to <code>OEGManager</code> — every method is
/// inherited, nothing is reimplemented — so behavior never drifts between the two names.
/// <code>OEGManager</code> keeps working unchanged for existing integrations; this class exists only to
/// give new games an Alogame-branded symbol to call instead.
/// <h2>Usage (Objective-C)</h2>
/// \code
/// [[AlogameManager sharedManager] showLoginWithCallback:^(OEGActionType type, id response, BOOL success, NSError *error) {
///     if (success) {
///         NSLog(@"Logged in!");
///     }
/// }];
///
/// \endcode
SWIFT_CLASS("_TtC8OegSdkV214AlogameManager")
@interface AlogameManager : OEGManager
@end

@class NSBundle;
@class NSCoder;
SWIFT_CLASS("_TtC8OegSdkV228ForgotPasswordViewController")
@interface ForgotPasswordViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8OegSdkV219LoginViewController")
@interface LoginViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

/// Action types returned in OEGAccountCallback
/// Matches legacy OEGManager.h enum values exactly
typedef SWIFT_ENUM(NSInteger, OEGActionType, open) {
  OEGActionTypeRegister = 0,
  OEGActionTypeLoginOEGID = 1,
  OEGActionTypeLoginFacebook = 2,
  OEGActionTypeLoginGoogle = 3,
  OEGActionTypeLoginApple = 4,
  OEGActionTypePlaynow = 5,
  OEGActionTypeLogout = 6,
  OEGActionTypeProfile = 7,
  OEGActionTypeChangePassword = 8,
  OEGActionTypeForgotPassword = 9,
  OEGActionTypeVerifyEmail = 10,
  OEGActionTypeVerifyPhone = 11,
  OEGActionTypeClose = 12,
};

SWIFT_ENUM_FWD_DECL(NSInteger, Environment)
/// OEG Analytics SDK - Adjust Integration
/// Matches Android’s <code>OEGAnalytics</code> public API structure.
SWIFT_CLASS("_TtC8OegSdkV212OEGAnalytics")
@interface OEGAnalytics : NSObject
/// Shared singleton instance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OEGAnalytics * _Nonnull shared;)
+ (OEGAnalytics * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Initialize Adjust SDK
/// \param appToken Adjust App Token
///
/// \param environment Sandbox or Production
///
/// \param eventTokenMap Optional mapping of event names to tokens
///
- (void)initializeWithAppToken:(NSString * _Nonnull)appToken environment:(enum Environment)environment eventTokenMap:(NSDictionary<NSString *, NSString *> * _Nonnull)eventTokenMap;
/// Track an event
/// \param eventNameOrToken Event name (from mapping) or direct token
///
/// \param parameters Optional callback parameters
///
- (void)logEvent:(NSString * _Nonnull)eventNameOrToken parameters:(NSDictionary<NSString *, NSString *> * _Nullable)parameters;
/// Track a purchase/revenue event
/// \param eventToken Adjust event token
///
/// \param price Amount
///
/// \param currency Currency code (USD, VND)
///
/// \param transactionId Unique transaction ID
///
/// \param productId Product ID
///
- (void)logPurchaseWithEventToken:(NSString * _Nonnull)eventToken price:(double)price currency:(NSString * _Nonnull)currency transactionId:(NSString * _Nullable)transactionId productId:(NSString * _Nullable)productId parameters:(NSDictionary<NSString *, NSString *> * _Nullable)parameters;
/// Track an event that carries revenue, keyed on the event’s own token.
/// Use for recharge / web_store / custom revenue events (e.g. first_recharge) where the game
/// dev must set the real Adjust revenue — passing the amount as a plain parameter does NOT count.
/// \param eventNameOrToken Event name (from mapping) or direct token — this is the Adjust event that records the revenue
///
/// \param revenue Amount (must be > 0 to be recorded)
///
/// \param currency ISO 4217 code (e.g. “VND”, “USD”)
///
/// \param orderId Unique order/transaction id for deduplication
///
/// \param parameters Optional extra callback parameters
///
- (void)logRevenue:(NSString * _Nonnull)eventNameOrToken revenue:(double)revenue currency:(NSString * _Nonnull)currency orderId:(NSString * _Nullable)orderId parameters:(NSDictionary<NSString *, NSString *> * _Nullable)parameters;
/// Enable/disable tracking (GDPR compliance)
- (void)setTrackingEnabled:(BOOL)enabled;
/// Legacy backward compatible method for tracking events with parameters
- (void)trackEventToken:(NSString * _Nonnull)eventToken parameters:(NSDictionary<NSString *, NSString *> * _Nullable)parameters;
/// Legacy backward compatible method for tracking revenue with parameters
- (void)trackEventToken:(NSString * _Nonnull)eventToken revenue:(double)revenue currency:(NSString * _Nullable)currency transactionId:(NSString * _Nullable)transactionId parameters:(NSDictionary<NSString *, NSString *> * _Nullable)parameters;
@end

/// Adjust environment enum
typedef SWIFT_ENUM(NSInteger, Environment, open) {
  EnvironmentSandbox = 0,
  EnvironmentProduction = 1,
};

/// Protocol for Unity/Native callbacks.
/// Designed to be implemented by native bridges.
/// Matches Android’s <code>OEGCallback</code> interface.
SWIFT_PROTOCOL("_TtP8OegSdkV211OEGCallback_")
@protocol OEGCallback
- (void)onSuccessWithPayload:(NSString * _Nonnull)payload;
- (void)onErrorWithCode:(NSInteger)code message:(NSString * _Nonnull)message;
@end

/// IAP status returned in OEGIAPCallback
/// Matches legacy OEGManager.h enum values exactly
typedef SWIFT_ENUM(NSInteger, OEGIAPStatus, open) {
  OEGIAPStatusPurchasing = 0,
  OEGIAPStatusPurchased = 1,
  OEGIAPStatusRestored = 2,
  OEGIAPStatusFailed = 3,
  OEGIAPStatusRequestError = 4,
  OEGIAPStatusVerified = 5,
};

/// OEG Payment SDK - StoreKit Integration
/// Provides in-app purchase functionality using StoreKit 2 (iOS 15+) or StoreKit 1 fallback.
/// Matches Android’s <code>OEGPayment</code> public API structure.
SWIFT_CLASS("_TtC8OegSdkV210OEGPayment") SWIFT_AVAILABILITY(ios,introduced=13.0) SWIFT_AVAILABILITY(macos,introduced=10.15)
@interface OEGPayment : NSObject
/// Shared singleton instance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OEGPayment * _Nonnull shared;)
+ (OEGPayment * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SKProductsRequest;
@class SKProductsResponse;
@class SKRequest;
@class SKPaymentQueue;
@class SKPaymentTransaction;
@interface OEGPayment (SWIFT_EXTENSION(OegSdkV2)) <SKPaymentTransactionObserver, SKProductsRequestDelegate>
- (void)productsRequest:(SKProductsRequest * _Nonnull)request didReceiveResponse:(SKProductsResponse * _Nonnull)response;
- (void)request:(SKRequest * _Nonnull)request didFailWithError:(NSError * _Nonnull)error;
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue updatedTransactions:(NSArray<SKPaymentTransaction *> * _Nonnull)transactions;
@end

@protocol OEGPushDelegate;
@class UNUserNotificationCenter;
@class UNNotification;
/// Decoupled Push Notification Manager.
/// Handles permission requests and token management.
/// Host app should pass the device token (APNS or FCM) via <code>setDeviceToken</code>.
SWIFT_CLASS("_TtC8OegSdkV27OEGPush") SWIFT_AVAILABILITY(ios,introduced=10.0) SWIFT_AVAILABILITY(macos,introduced=10.14)
@interface OEGPush : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OEGPush * _Nonnull shared;)
+ (OEGPush * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Request Push Notification Permission
/// \param completion (Granted, Error?)
///
- (void)requestAuthorizationWithCompletion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
/// Request the OS notification permission.
/// Unified with Android <code>OEGPush.requestNotificationPermission(callback:)</code> — same name,
/// same <code>granted: Bool</code> result. Use this from cross-platform code; on iOS it wraps
/// <code>requestAuthorization</code> and drops the error. [completion] is invoked on the main thread.
- (void)requestNotificationPermissionWithCompletion:(void (^ _Nonnull)(BOOL))completion;
/// Set the device token (Hex String or FCM Token)
/// \param token String representation of the token
///
- (void)setDeviceToken:(NSString * _Nonnull)token;
/// Helper to convert APNS Data to Hex String
- (void)didRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
- (void)registerForPushNotificationsWithApplication:(UIApplication * _Nonnull)application;
- (void)didRegisterWithToken:(NSData * _Nonnull)deviceToken;
/// Delegate for exposing push data to game engines (Cocos Creator, Egret, Unity)
@property (nonatomic, weak) id <OEGPushDelegate> _Nullable delegate;
/// Handle incoming remote notification data payload
/// \param userInfo The notification payload dictionary
///
- (void)handleRemoteNotification:(NSDictionary * _Nonnull)userInfo;
/// Handle incoming notification (foreground)
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center willPresent:(UNNotification * _Nonnull)notification withCompletionHandler:(void (^ _Nonnull)(UNNotificationPresentationOptions))completionHandler;
@end

/// Protocol for game engines to receive push notification data
SWIFT_PROTOCOL("_TtP8OegSdkV215OEGPushDelegate_")
@protocol OEGPushDelegate
@optional
/// Called when a push notification is received
- (void)oegPushDidReceiveNotificationWithUserInfo:(NSDictionary * _Nonnull)userInfo;
/// Called when device token is updated
- (void)oegPushDidUpdateToken:(NSString * _Nonnull)token;
@end

/// Main entry point for OEG SDK v2.
/// Matches Android’s <code>OEGFrameworks</code> singleton but renamed to <code>OegSdkCore</code> per convention.
SWIFT_CLASS("_TtC8OegSdkV210OegSdkCore") SWIFT_AVAILABILITY(ios,introduced=13.0) SWIFT_AVAILABILITY(macos,introduced=10.15)
@interface OegSdkCore : NSObject
/// Shared singleton instance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OegSdkCore * _Nonnull shared;)
+ (OegSdkCore * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Initialization state
@property (nonatomic, readonly) BOOL isInitialized;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Check if SDK is ready
- (BOOL)checkInitialized SWIFT_WARN_UNUSED_RESULT;
/// Set the active Game Character/Role info (for tracking and dashboard display).
/// This is a convenience method that delegates to OEGAuth.shared.setGameRole().
/// \param serverId Server ID (required)
///
/// \param serverName Server display name (optional)
///
/// \param roleId Character/Role ID (required)
///
/// \param roleName Character/Role display name (optional)
///
/// \param level Character level (optional)
///
+ (void)setGameRoleWithServerId:(NSString * _Nonnull)serverId serverName:(NSString * _Nullable)serverName roleId:(NSString * _Nonnull)roleId roleName:(NSString * _Nullable)roleName level:(NSInteger)level;
/// Clear the active Game Character/Role without logging the account out.
/// This is a convenience method that delegates to OEGAuth.shared.logoutGameRole().
/// The SDK only clears its own state, then invokes <code>callback</code> — it does not navigate
/// anywhere. Use the callback to move the game to its own switch-server screen.
+ (void)logoutGameRoleWithCallback:(void (^ _Nonnull)(void))callback;
/// The active Game Character/Role, as a dictionary — <code>nil</code> if none is set. <code>OEGGameRole</code> is
/// a Swift struct and can’t be bridged to Objective-C directly, so this is the ObjC-visible
/// equivalent of reading <code>OEGAuth.gameRole</code> from Swift. Keys: serverId, serverName, roleId,
/// roleName (all NSString, absent when not provided), level (NSNumber, absent when not set).
+ (NSDictionary<NSString *, id> * _Nullable)getGameRole SWIFT_WARN_UNUSED_RESULT;
@end

/// Builder for constructing SDK configuration
SWIFT_CLASS("_TtCC8OegSdkV210OegSdkCore7Builder")
@interface Builder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (Builder * _Nonnull)setGameId:(NSInteger)gameId SWIFT_WARN_UNUSED_RESULT;
- (Builder * _Nonnull)setApiBaseUrl:(NSString * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
/// Selects the hardcoded dev vs. production API host (see SdkEnvironment).
/// Ignored if setApiBaseUrl was also called.
- (Builder * _Nonnull)setDebugEnv:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (Builder * _Nonnull)setSentryDsn:(NSString * _Nonnull)dsn SWIFT_WARN_UNUSED_RESULT;
- (Builder * _Nonnull)setAdjustConfigWithAppToken:(NSString * _Nonnull)appToken environment:(NSString * _Nonnull)environment SWIFT_WARN_UNUSED_RESULT;
/// Set the maintain polling interval in seconds.
/// Default: 60. Minimum: 30 (clamped). 0 disables polling entirely.
- (Builder * _Nonnull)setMaintainPollingInterval:(NSInteger)seconds SWIFT_WARN_UNUSED_RESULT;
- (void)build;
@end

SWIFT_CLASS("_TtC8OegSdkV221ProfileViewController")
@interface ProfileViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8OegSdkV227ResetPasswordViewController")
@interface ResetPasswordViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8OegSdkV227UpdateProfileViewController")
@interface UpdateProfileViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8OegSdkV220VerifyViewController")
@interface VerifyViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
